# Site settings
theme: jekyll-theme-cayman
title: "RiRi at Creai"
description: "개발하며 배운 것들. #iOS #Objective-C #Swift"
url: http://riri.creai.net # the base hostname & protocol for your site
email: riri@creai.net
twitter_username: ririsid
github_username: ririsid
google_analytics: UA-89960156-1
