# Site settings
title: RiRi at Creai
email: riri@creai.net
description: > # this means to ignore newlines until "baseurl:"
  초보 개발자 RiRi가 개발하며 배운 것들. #iOS #Objective-C #Swift
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://riri.creai.net" # the base hostname & protocol for your site
twitter_username: ririsid
github_username:  ririsid

# Build settings
markdown: redcarpet
highlighter: rouge
